spring.application.name=skillmentor
spring.profiles.active=${PROFILE}

server.port=8081

spring.datasource.url=${DATABASE_URL}
#jdbc:postgresql://localhost:5432/skill_mentor_v2
#jdbc:postgresql://host.docker.internal:5432/skill_mentor_v2 \
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=60000ms

# Cache Configuration
app.cache.enabled=${CACHE_ENABLED:true}
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.key-prefix=skillmentor:cache:
spring.cache.redis.use-key-prefix=true